# _config.yml en la raíz

title: "ComicPlan"
description: "Web y Blog de ComicPlan"
baseurl: ""  # si usás GitHub Pages con dominio personalizado, dejar así
url: "http://localhost:4000"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/blog/page/:num"  # <-- Ojo, para paginación del blog

# Blog URL y estructura
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Para que las páginas personalizadas tengan buen permalink
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages
  - _drafts
  - _layouts
  - _includes
  - _sass

# Etiquetas (para jekyll/tagging)
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
