# _config.yml en la raíz

title: "ComicPlan"
description: "Web y Blog de ComicPlan"
baseurl: ""  # si usás GitHub Pages con dominio personalizado, dejar así
url: "https://comicplan.com"

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 5
paginate_path: "/blog/page/:num/"  # <-- Ojo, para paginación del blog

# Blog URL y estructura
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Para que las páginas personalizadas tengan buen permalink
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title/

include:
  - _pages
  - _drafts
  - _layouts
  - _includes
  - _sass
  - blog

# Excluir explícitamente todo lo que no sea parte del blog
exclude:
  - index.html
  - styles.css
  - provincias.js
  - script.js
  - readme.md
  - images/
  - js/

# Procesar solo los archivos dentro de la carpeta blog
keep_files:
  - index.html
  - styles.css
  - provincias.js
  - script.js
  - images
  - js

# Etiquetas (para jekyll/tagging)
tag_page_dir:         blog/tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed
